ProyectoDesarrollo/Controllers/ProyectoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using ProyectoDesarrollo.Models;
using ProyectoDesarrollo.Service;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Numerics;

namespace ProyectoDesarrollo.Controllers
{
    public class ProyectoController : Controller
    {
        private readonly IUsuarios _IUsuarios;
        private readonly IDoctor _IDoctor;
        private readonly ISecretaria _ISecretaria;
        private readonly IAdministrador _IAdministrador;
        private readonly IPaciente _IPaciente;
        private readonly IEspecialidad _IEspecialidad;
        private readonly IEstados _IEstados;
        private readonly IHorario _Horario;
        private readonly ICita _ICita;
        private readonly IGenero _IGenero;
        public ProyectoController(IUsuarios usu, IDoctor doc, ISecretaria sec, IAdministrador admin, IPaciente pac, IEspecialidad especialidad, IEstados estados, IHorario horario, ICita cita, IGenero genero)
        {
            _IUsuarios = usu;
            _IDoctor = doc;
            _ISecretaria = sec;
            _IAdministrador = admin;
            _IPaciente = pac;
            _IEspecialidad = especialidad;
            _IEstados = estados;
            _Horario = horario;
            _ICita = cita;
            _IGenero = genero;
        }

        public IActionResult Inicio()
        {
            return View();
        }
        /*Iniciar sesion - Secretaria*/
        public IActionResult InSecretaria(string usuS, string contraS)
        {
            var resultado = _IUsuarios.VerificarS(usuS, contraS);
            if (resultado == "true")
            {
                return Redirect($"/Proyecto/PrincipalSecretaria?usuS={usuS}#Inicios");
            }
            else
            {
                return View();
            }
        }
        /*Iniciar sesion - Doctor*/
        public IActionResult InDoctor(string usuD, string contraD)
        {
            var resultado = _IUsuarios.VerificarD(usuD, contraD);
            if (resultado == "true")
            {
                return Redirect($"/Proyecto/PrincipalDoctor?usuD={usuD}#Inicios");
            }
            else
            {
                return View();
            }
        }
        /*Iniciar sesion - Paciente*/
        public IActionResult InPaciente(string usuP, string contraP)
        {
            var resultado = _IUsuarios.VerificarP(usuP, contraP);
            if (resultado == "true")
            {
                return Redirect($"/Proyecto/PrincipalPaciente?usuP={usuP}#Inicios");
            }
            else
            {
                return View();
            }
        }
        /*Iniciar sesion - Administrador*/
        public IActionResult InAdministrador(string usuA, string contraA)
        {
            var resultado = _IUsuarios.VerificarA(usuA, contraA);
            if (resultado == "true")
            {
                return Redirect($"/Proyecto/PrincipalAdministrador?usuA={usuA}#Inicios");
            }
            else
            {
                return View();
            }
        }
        /*Pagina principal - Secretaria*/
        public IActionResult PrincipalSecretaria(string usuS)
        {
            if (string.IsNullOrEmpty(usuS))
            {
                usuS = TempData["usuS"] as string;
            }
            TempData["usuS"] = usuS;
            ViewBag.perfil = _ISecretaria.PerfilS(usuS);
            ViewBag.especialidad = _IEspecialidad.GetDistinctEspecialidad();
            ViewBag.genero = _IPaciente.GetDistinctGeneros();
            ViewBag.doctor = _IDoctor.GetDoctors();
            ViewBag.pacientes = _IPaciente.GetPacientes();
            ViewBag.citas = _ICita.GetCitas();
            ViewBag.estados = _IEstados.GetDistinctEstado();
            ViewBag.horario = _Horario.GetHorarios();
            ViewBag.especDoc = _IEspecialidad.GetEspecialidadDoc();
            ViewBag.contadorDoctor = _IDoctor.CantidadDoctores();
            ViewBag.contadorPaciente = _IPaciente.CantidadPacientes();
            ViewBag.contadorCitas = _ICita.CantidadCitas();
            ViewBag.contadorEspecilidades = _IEspecialidad.cantidadEspecilidadesporDoctor();
            return View();
        }

        /*Pagina principal - Doctor*/
        public IActionResult PrincipalDoctor(string usuD)
        {
            if (string.IsNullOrEmpty(usuD))
            {
                usuD = TempData["usuD"] as string;
            }
            TempData["usuD"] = usuD;
            ViewBag.perfil = _IDoctor.PerfilD(usuD);
            ViewBag.genero = _IPaciente.GetDistinctGeneros();
            ViewBag.doctor = _IDoctor.GetDoctors();
            ViewBag.pacientes = _IPaciente.GetPacientes();
            ViewBag.cita = _ICita.GetCitasporDoctor(usuD);
            ViewBag.contadorcitas = _ICita.CantidadCitasporDoctores(usuD);
            ViewBag.contadorPaciente = _IPaciente.CantidadPacientes();
            return View();

        }
        /*Pagina principal - Paciente*/
        public IActionResult PrincipalPaciente(string usuP)
        {
            if (string.IsNullOrEmpty(usuP))
            {
                usuP = TempData["usuP"] as string;
            }
            TempData["usuP"] = usuP;
            ViewBag.perfil = _IPaciente.PerfilP(usuP);
            ViewBag.cita = _ICita.GetCitasByPaciente(usuP);
            ViewBag.contadorcitas = _ICita.CantidadCitasporPacientes(usuP);
            return View();
        }
        /*Pagina principal - Administrador*/
        public IActionResult PrincipalAdministrador(string usuA)
        {
            if (string.IsNullOrEmpty(usuA))
            {
                usuA = TempData["usuA"] as string;
            }
            TempData["usuA"] = usuA;
            ViewBag.perfil = _IAdministrador.PerfilA(usuA);
            ViewBag.especialidad = _IEspecialidad.GetDistinctEspecialidad();
            ViewBag.genero = _IPaciente.GetDistinctGeneros();
            ViewBag.secretarias = _ISecretaria.GetSecretarias();
            ViewBag.doctor = _IDoctor.GetDoctors();
            ViewBag.pacientes = _IPaciente.GetPacientes();
            ViewBag.contadorDoctor = _IDoctor.CantidadDoctores();
            ViewBag.contadorPaciente = _IPaciente.CantidadPacientes();
            ViewBag.contadorSecretaria = _ISecretaria.CantidadSecretarias();
            ViewBag.contadorEspecilidades = _IEspecialidad.cantidadEspecilidadesporDoctor();
            return View();
        }
        /*Eliminar Paciente - A, D Y S*/
        public IActionResult EliminarpacienteA(int id)
        {
            _IPaciente.RemoveP(id);
            return Redirect("/Proyecto/PrincipalAdministrador#Pacientes");
        }
        public IActionResult EliminarpacienteD(int id)
        {
            _IPaciente.RemoveP(id);
            return Redirect("/Proyecto/PrincipalDoctor#Pacientes");
        }
        public IActionResult EliminarpacienteS(int id)
        {
            _IPaciente.RemoveP(id);
            return Redirect("/Proyecto/PrincipalSecretaria#Pacientes");
        }
        /*Eliminar doctor A y S*/
        public IActionResult EliminardoctorA(int id)
        {
            _IDoctor.RemoveD(id);
            return Redirect("/Proyecto/PrincipalAdministrador#Doctores");
        }
        public IActionResult EliminardoctorS(int id)
        {
            _IDoctor.RemoveD(id);
            return Redirect("/Proyecto/PrincipalSecretaria#Doctores");
        }
        /*Eliminar secretaria*/

        public IActionResult Eliminarsecretaria(int id)
        {
            _ISecretaria.RemoveS(id);
            return Redirect("/Proyecto/PrincipalAdministrador#Secretarias");
        }
        public IActionResult EliminarCitaD(int id)
        {
            _ICita.RemoveC(id);
            return Redirect("/Proyecto/PrincipalDoctor#Citas");
        }
        public IActionResult EliminarCitaS(int id)
        {
            _ICita.RemoveC(id);
            return Redirect("/Proyecto/PrincipalSecretaria#Reservaciones");
        }
        public IActionResult EliminarCitaP(int id)
        {
            _ICita.RemoveC(id);
            return Redirect("/Proyecto/PrincipalPaciente#ReservarCitas");
        }
        /*Editar secretaria con id*/
        public IActionResult Editarsecretaria(int id)
        {
            return View(_ISecretaria.SecretariaId(id));
        }
        /*Editar secretaria*/
        public IActionResult ModificarSecretaria(Secretarium secretaria)
        {
            _ISecretaria.editDetails(secretaria);
            return Redirect("/Proyecto/PrincipalAdministrador#Secretarias");
        }
        /*Editar doctor con id*/
        public IActionResult Editardoctor(int id)
        {
            ViewBag.especialidad = _IEspecialidad.GetDistinctEspecialidad();
            return View(_IDoctor.DoctorId(id));
        }
        public IActionResult EditardoctorS(int id)
        {
            ViewBag.especialidad = _IEspecialidad.GetDistinctEspecialidad();
            return View(_IDoctor.DoctorId(id));
        }
        /*Editar doctor para administrador*/
        public IActionResult ModificarDoctor(Doctor doc)
        {
            _IDoctor.editDetails(doc);
            return Redirect("/Proyecto/PrincipalAdministrador#Doctores");
        }
        /*Editar doctor para secretaria*/
        public IActionResult ModificarDoctorS(Doctor doc)
        {
            _IDoctor.editDetails(doc);
            return Redirect("/Proyecto/PrincipalSecretaria#Doctores");
        }

        /*Editar paciente con id*/
        public IActionResult EditarpacienteS(int id)
        {
            ViewBag.genero = _IPaciente.GetDistinctGeneros();
            return View(_IPaciente.PacienteId(id));
        }
        public IActionResult EditarpacienteA(int id)
        {
            ViewBag.genero = _IPaciente.GetDistinctGeneros();
            return View(_IPaciente.PacienteId(id));
        }

ProyectoDesarrollo/Views/Proyecto/EditarCitaS.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ProyectoDesarrollo.Models.Cita
@{
}
<html>
<head>
    <link href="~/css/agregar.css" rel="stylesheet" />
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://kit.fontawesome.com/fc0e7e3519.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="otraCabecera">
        <label class="IniciarSesion">Clínica SaludTotal</label>
        <i class="fas fa-clinic-medical"></i>
    </div>
        <form class="row g-3" asp-controller="Proyecto" asp-action="GrabarCita">
            <div class="col-md-6">
                <input type="hidden" asp-for="IdCitas" placeholder="Ingrese el codigo" />
                <label class="form-label genDL">PACIENTE</label>
                <select class="form-select genD" asp-for="IdPaciente">
                    <option value="" selected disabled>Seleccione un paciente</option>
                    @foreach (var paciente in ViewBag.pacientes)
                    {
                        var paciente1 = (ProyectoDesarrollo.Models.Paciente)paciente;
                        <option value="@paciente1.IdPaciente">@paciente1.NomPaciente</option>
                    }
                </select>
                <label class="form-label genDL">ESTADO DE PACIENTE</label>
                <select class="form-select genD" asp-for="IdEstados">
                    <option value="" selected disabled>Seleccione estado del paciente</option>
                    @foreach (var estado in ViewBag.estados)
                    {
                        var estado1 = (ProyectoDesarrollo.Models.Estado)estado;
                        <option value="@estado1.IdEstados">@estado1.NomEstados</option>
                    }
                </select>
                <label class="form-label genDL">ESPECIALIDAD</label>
                <select class="form-select genD" asp-for="IdEspecialidad">
                    <option value="" selected disabled>Seleccione especialidad</option>
                    @foreach (var especialidad in ViewBag.especDoc)
                    {
                        var especialidad1 = (ProyectoDesarrollo.Models.Especialidad)especialidad;
                        <option value="@especialidad1.IdEspecialidad">@especialidad1.NomEspecialidad</option>
                    }
                </select>
            </div>
            <div class="col-md-6">
                <label class="form-label genDL">DOCTOR</label>
                <select class="form-select genD" asp-for="IdDoctor">
                    <option value="" selected disabled>Seleccione un doctor</option>
                    @foreach (var doctor in ViewBag.doctor)
                    {
                        var doctor1 = (ProyectoDesarrollo.Models.Doctor)doctor;
                        <option value="@doctor1.IdDoctor">@doctor1.NomDoctor</option>
                    }
                </select>
                <label class="form-label fecPL">FECHA</label>
                <input class="form-control fecP" type="date" asp-for="FechaCitas" placeholder="fecha de cita" />
                <label class="form-label genPL">HORARIO</label>
                <select class="form-select genP" asp-for="IdHorario">
                    <option value="" selected disabled>Seleccione un horario</option>
                    @foreach (var horario in ViewBag.horario)
                    {
                        var horario1 = (ProyectoDesarrollo.Models.Horario)horario;
                        <option value="@horario1.IdHorario">@horario1.Hora</option>
                    }
                </select>
            <div class="col-12">
                <button class="btn btn-primary buttonS" asp-action="ModificarCitaS">MODIFICAR</button>
            </div>
        </div>
    </form>
</body>
</html>

ProyectoDesarrollo/Views/Proyecto/EditarDoctorP.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ProyectoDesarrollo.Models.Doctor
@{
}
<html>
<head>
    <link href="~/css/agregar.css" rel="stylesheet" />
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://kit.fontawesome.com/fc0e7e3519.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="otraCabecera">
        <label class="IniciarSesion">Clínica SaludTotal</label>
        <i class="fas fa-clinic-medical"></i>
    </div>

    <form class="row g-3">
        <div class="col-md-6">
            <input type="hidden" asp-for="IdDoctor" placeholder="Ingrese el codigo" />
            <label class="form-label nomDL">NOMBRE</label>
            <input class="form-control nomD" type="text" asp-for="NomDoctor" placeholder="Ingrese el nombre" />
            <span asp-validation-for="NomDoctor" class="text-danger"></span>
            <label class="form-label apeDL">APELLIDO</label>
            <input class="form-control apeD" type="text" asp-for="ApeDoctor" placeholder="Ingrese el apellido" />
            <span asp-validation-for="ApeDoctor" class="text-danger"></span>
            <label class="form-label dniDL">DNI</label>
            <input class="form-control dniD" type="number" asp-for="DniDoctor" placeholder="Ingrese el dni" />
            <span asp-validation-for="DniDoctor" class="text-danger"></span>
            <label class="form-label genDL">ESPECIALIDAD</label>
        </div>
        <div class="col-md-6">
            <select class="form-select genD" asp-for="IdEspecialidad">
                @foreach (var doctor in ViewBag.especialidad)
                {
                    var doctor1 = (ProyectoDesarrollo.Models.Especialidad)doctor;
                    <option value="@doctor1.IdEspecialidad">@doctor1.NomEspecialidad</option>
                }
            </select>
            <span asp-validation-for="IdEspecialidad" class="text-danger"></span>
            <label class="form-label telDL">TELEFONO</label>
            <input class="form-control telD" type="number" asp-for="TelDoctor" placeholder="Ingrese el telefono" />
            <span asp-validation-for="TelDoctor" class="text-danger"></span>
            <label class="form-label usuDL">USUARIO</label>
            <input class="form-control usuD" type="text" asp-for="UsuDoctor" placeholder="Ingrese el usuario" />
            <span asp-validation-for="UsuDoctor" class="text-danger"></span>
            <label class="form-label contraDL">CONTRASEÑA</label>
            <input class="form-control contraD" type="text" asp-for="ContraDoctor" placeholder="Ingrese la contraseña" />
            <span asp-validation-for="ContraDoctor" class="text-danger"></span>
            <div class="col-12">
                <button class="btn btn-primary buttonD" asp-action="ModificarDoctorP">MODIFICAR</button>
            </div>
        </div>
    </form>
</body>
</html>

ProyectoDesarrollo/Views/Proyecto/InDoctor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ProyectoDesarrollo.Models.Doctor
@{
}
<html>
    <head>
        <link href="~/css/Estilos.css" rel="stylesheet" />
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <script src="https://kit.fontawesome.com/fc0e7e3519.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="otraCabecera">
        <label class="IniciarSesion">Clínica SaludTotal</label>
        <i class="fas fa-clinic-medical"></i>
    </div>
    <label class="titulo">DOCTOR LOGIN</label>
    <form class="IniciarSesion">
        <div class ="IniciarSesion">
            <input class="IniciarDoctor" type="text" placeholder="User" name="usuD"/><br  />
            <input class="IniciarDoctor" type="password" placeholder="Password" name="contraD"/><br />
                <button class="IniciarDoctor">LOGIN</button>
                <button class="IniciarDoctor" asp-action="Inicio">RETURN</button>
            </div>
        </form>
    </body>
    <script src="~/js/Validar.js"></script>
</html>

ProyectoDesarrollo/Views/Proyecto/PrincipalDoctor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ProyectoDesarrollo.Models.Modelos
@{
}
<html>
<head>
    <link href="~/css/EstilosPaginaPrincipal.css" rel="stylesheet" />
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="https://kit.fontawesome.com/fc0e7e3519.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/font-awesome.min.css">
    <script src="~/js/JavaScript.js"></script>
</head>
    <body>

        <nav>
            <ul>
                <li>
                    <a asp-action="Inicio" id="logoLink" class="logo">
                        <i class="fas fa-code"></i>
                        <span class="nav-item">Clínica SaludTotal</span>
                    </a>
                </li>

                <li>
                    <a href="#Inicios">
                        <i class="fas fa-home"></i>
                        <span class="nav-item">Inicio</span>
                    </a>
                </li>

                <li>
                    <a href="#Perfil">
                        <i class="fas fa-user"></i>
                        <span class="nav-item">Perfil (Doctor)</span>
                    </a>
                </li>

                <li>
                    <a href="#Citas">
                        <i class="far fa-calendar-check"></i>
                        <span class="nav-item">Citas (@ViewBag.contadorcitas)</span>
                    </a>
                </li>

                <li>
                    <a href="#Pacientes">
                        <i class="fa fa-users"></i>
                        <span class="nav-item">Pacientes (@ViewBag.contadorPaciente)</span>
                    </a>
                </li>

                <li>
                    <a asp-action ="Inicio" class="logout" id="logoutLink">
                        <i class="fas fa-sign-out-alt"></i>
                        <span class="nav-item">Salir</span>
                    </a>
                </li>
            </ul>
        </nav>
        <main>
            <section id="Inicios" class="pagina">
                <form class="inicio">
                <h1>BIENVENIDO</h1>
                <h2>Bienvenido a la Clinica SaludTotal</H2>
                <hr />

                <h3>Horario:</h3>
                <label>Desde: 7:00:00</label><br />
                <label>Hasta: 18:00:00</label><br />
                <hr />

                <h3>Direccion:</h3>
                <label>Av. Santa Rosa #1234</label><br />
                <hr />

                <h3>Contactos:</h3>
                <label>Telfono: 951-120-000</label><br />
                <label>Correo: ClinicaSaludTotal@gmail.com</label><br />
                </form>
                <img src="~/css/hospital_health_clinic_urban_buildings_medical_icon_128575.png" />
                
            </section>

            <section id="Perfil" class="pagina">
                <h1 class="Listar">Perfil:</h1>
                <form class="Listar form-container">
                    <table class="table table-bordered">
                        <tr class="encabezado">
                            <td>CODIGO</td>
                            <td>NOMBRE</td>
                            <td>APELLIDO</td>
                            <td>DNI</td>
                            <td>TELEFONO</td>
                            <td>ESPECIALIDAD</td>
                            <td>USUARIO</td>
                            <td>CONTRASEÑA</td>
                            <td></td>
                        </tr>
                        <tbody>
                            <tr>
                                <td>@ViewBag.perfil.IdDoctor</td>
                                <td>@ViewBag.perfil.NomDoctor</td>
                                <td>@ViewBag.perfil.ApeDoctor</td>
                                <td>@ViewBag.perfil.DniDoctor</td>
                                <td>@ViewBag.perfil.TelDoctor</td>
                                <td>@ViewBag.perfil.IdEspecialidadNavigation?.NomEspecialidad</td>
                                <td>@ViewBag.perfil.UsuDoctor</td>
                                <td>@ViewBag.perfil.ContraDoctor</td>
                                 <td><a asp-action="EditarDoctorP" asp-route-id="@ViewBag.perfil.IdDoctor" class="EditarD"><i class='fas fa-edit'></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </section>

            <section id="Citas" class="pagina">
                <h1 class="Listar">Gestion de citas:</h1>
                <form class="Listar form-container">
                    <table class="table table-bordered">
                    <tr class="encabezado">
                        <td>CODIGO</td>
                        <td>FECHA</td>
                        <td>PACIENTE</td>
                        <td></td>
                        <td>ESTADO</td>
                        <td>HORA</td>
                        <td>ESPECIALIDAD</td>
                        <td></td>
                    </tr>
                    <tbody>
                        @foreach (var item in ViewBag.cita)
                    {
                        var citaObj = (ProyectoDesarrollo.Models.Cita)item;
                     <tr>
                        <td>@citaObj.IdCitas</td>
                        <td>@citaObj.FechaCitas.ToShortDateString()</td>
                        <td>@citaObj.IdPacienteNavigation?.NomPaciente</td>
                        <td>@citaObj.IdPacienteNavigation?.ApePaciente</td>
                        <td>@citaObj.IdEstadosNavigation?.NomEstados</td>
                        <td>@citaObj.IdHorarioNavigation?.Hora</td>                        
                        <td>@citaObj.IdEspecialidadNavigation?.NomEspecialidad</td>
                        <td><a onclick="abrirModalDC('@citaObj.IdCitas')" class="EliminarS"><i class="fa fa-trash-o"></i></a></td>
                     </tr>
                    }
                </tbody>
                </table>
                </form>  
            </section>

            <section id="Pacientes" class="pagina">
                <h1 class="Listar">Gestion de pacientes:</h1>
                <form class="Listar form-container">
                    <button  onclick="abrirGrabarP()" class="crear">Registrar pacientes</button>
                        <table class="table table-bordered">
                            <tr class="encabezado">
                                <td>CODIGO</td>
                                <td>NOMBRE</td>
                                <td>APELLIDO</td>
                                <td>DNI</td>
                                <td>FECHA DE NACIMIENTO</td>
                                <td>GENERO</td>
                                <td>TELEFONO</td>
                                <td>USUARIO</td>
                                <td>CONTRASEÑA</td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tbody>
                                @foreach (var item in ViewBag.pacientes)
                            {
                                var pacienteObj = (ProyectoDesarrollo.Models.Paciente)item;
                             <tr>
                                <td>@pacienteObj.IdPaciente</td>
                                <td>@pacienteObj.NomPaciente</td>
                                <td>@pacienteObj.ApePaciente</td>
                                <td>@pacienteObj.DniPaciente</td>
                                <td>@pacienteObj.NacPaciente.ToShortDateString()</td>
                                <td>@pacienteObj.IdGeneroNavigation?.NomGenero</td>                        
                                <td>@pacienteObj.TelPaciente</td>
                                <td>@pacienteObj.UsuPaciente</td>
                                <td>@pacienteObj.ContraPaciente</td>
                                <td><a onclick="abrirModalDP('@pacienteObj.IdPaciente')" class="EliminarP"><i class="fa fa-trash-o"></i></a></td>
                                <td><a asp-action="EditarpacienteD" asp-route-id="@pacienteObj.IdPaciente" class="EditarP"><i class='fas fa-edit'></i></a></td>
                             </tr>

                            }
                        </tbody>
                        </table>
                </form>
            </section>

            <!-- /*Eliminar Paciente*/ -->
            <div id="miModalDP" class="modal">
            <div class="modal-contenido">
                <span class="cerrar" onclick="cerrarModalDP()">&times;</span>
                <h2>Confirmar eliminación</h2>
                <p>¿Estás seguro de que deseas eliminar este paciente?</p>
                <button class="btnEliminar" onclick="eliminarPacienteDP()">Aceptar</button>
                <button class="btnEliminarM" onclick="cerrarModalDP()">Cancelar</button>
            </div>
            </div>

            <!-- /*Eliminar cita*/ -->
            <div id="miModalDC" class="modal">
            <div class="modal-contenido">
                <span class="cerrar" onclick="cerrarModalDC()">&times;</span>
                <h2>Confirmar eliminación</h2>
                <p>¿Estás seguro de que deseas eliminar esta cita?</p>
                <button class="btnEliminar" onclick="eliminarCitaDC()">Aceptar</button>
                <button class="btnEliminarM" onclick="cerrarModalDC()">Cancelar</button>
            </div>
            </div>

            <!-- /*Grabar Paciente*/ -->
            <div id="GrabarP" class="modal">
            <div class="modal-contenidoP">
                <span class="cerrar" onclick="cerrarGrabarP()">&times;</span>
                 <form class="row g-3" asp-controller="Proyecto" asp-action="GrabarpacienteD">
                    <div class="col-md-6">
                        <input type="hidden" asp-for="Paciente.IdPaciente" placeholder="Ingrese el codigo" />
                        <label class="form-label nomPL">NOMBRE</label>
                        <input class="form-control nomP" type="text" asp-for="Paciente.NomPaciente" placeholder="Ingrese el nombre" />
                        <label class="form-label apePL">APELLIDO</label>
                        <input class="form-control apeP" type="text" asp-for="Paciente.ApePaciente" placeholder="Ingrese el apellido" />
                        <label class="form-label dniPL">DNI</label>
                        <input class="form-control dniP" type="text" asp-for="Paciente.DniPaciente" placeholder="Ingrese el dni" />
                        <label class="form-label fecPL">FECHA DE NACIMIENTO</label>
                        <input class="form-control fecP" type="date" asp-for="Paciente.NacPaciente" placeholder="fecha de nacimiento" />
                    </div>
                    <div class="col-md-6">
                        <label class="form-label genPL">GENERO</label>
                        <select class="form-select genP" asp-for="Paciente.IdGenero">
                        <option value=""selected disabled>Seleccione su genero</option>
                            @foreach (var paciente in ViewBag.genero)
                            {
                                var paciente1 = (ProyectoDesarrollo.Models.Genero)paciente;
                                <option value="@paciente1.IdGenero">@paciente1.NomGenero</option>
                            }
                        </select>
                        <label class="form-label telPL">TELEFONO</label>
                        <input class="form-control telP" type="text" asp-for="Paciente.TelPaciente" placeholder="Ingrese el telefono" />
                        <label class="form-label usuPL">USUARIO</label>
                        <input class="form-control usuP" type="text" asp-for="Paciente.UsuPaciente" placeholder="Ingrese el usuario" />
                        <label class="form-label contraPL">CONTRASEÑA</label>
                        <input class="form-control contraP" type="password" asp-for="Paciente.ContraPaciente" placeholder="Ingrese la contraseña" />
                        <button class="btnEliminarAP">Aceptar</button>
                    </div>
                </form>
                <button class="btnEliminarCP" onclick="cerrarGrabarP()">Cancelar</button>
            </div>
            </div>
        </main>
    </body>
    <script src="~/js/PaginasPrincipales.js"></script>
    <script src="~/js/JavaScript.js"></script>
</html>